name: Node.js CI

on:
  push:
    branches:
      - new
  pull_request:
    branches:
      - new
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Set up git hash
        run: echo \"$(git rev-parse --short HEAD)\" > assets/hash.json
      - name: Build project
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Post check build ID
        run: |
          cat .output/public/index.html | grep builds/meta
          cat .output/public/_nuxt/builds/latest.json

      # 你可以添加更多步骤，例如：
      # - name: Lint code
      #   run: pnpm lint
      # - name: Deploy (if applicable)
      #   run: pnpm deploy
